"use strict";
const table = document.getElementById("table");
const ctx = table.getContext("2d");
ctx.font = "2rem serif";
ctx.textAlign = "center";
ctx.textBaseline = "middle";
ctx.fillText("hello world", 200, 200);
ctx.beginPath();
ctx.lineWidth = 2;
ctx.strokeStyle = "aquamarine";
ctx.arc(200, 200, 150, 0, 2 * Math.PI);
ctx.stroke();
